# Generated by Django 3.0.5 on 2020-10-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_img',
            field=models.ImageField(default='default.jpg', upload_to='project_pics/'),
        ),
    ]
