# Generated by Django 3.0.5 on 2020-10-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project_project_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_github',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_url',
            new_name='url',
        ),
    ]
